const mockComments = [
  "This song is like a rollercoaster, it goes up and down and makes me nauseous.",
  "I feel like I just got punched in the face by this song, in a good way.",
  "If this song were a person, it would be that one weird uncle everyone has.",
  "I love this song, it's like a mix between an angel choir and a dying cat.",
  "This song has more ups and downs than my ex's emotional state.",
  "I'm pretty sure this song is actually just a remix of a fax machine.",
  "This song is like a mosquito buzzing in my ear, but I can't help but love it.",
  "Listening to this song is like getting hit by a wave of happiness, followed by a wave of confusion.",
  "This song is so catchy, I feel like I need a tetanus shot.",
  "If this song were a person, they would definitely be a drama queen.",
  "I don't know what this song is trying to say, but I'm pretty sure it involves a goat sacrifice.",
  "I can't tell if this song is amazing or terrible, but either way I can't stop listening.",
  "This song is like a crazy party in my earbuds, and I'm totally here for it.",
  "I'm pretty sure this song is the reason aliens won't talk to us.",
  "This song is like a cheeseburger with extra cheese, it's probably not good for me but I don't care.",
  "This song makes me want to dance like a flamingo on a hot tin roof.",
  "I don't know what this song is about, but I'm pretty sure it involves a chicken and a kazoo.",
  "Listening to this song is like taking a trip to a strange, wonderful alternate universe.",
  "This song is like a hug from a really drunk friend, it's comforting but also kind of concerning.",
  "I can't tell if this song is genius or madness, but either way it's entertaining.",
  "This song is like a unicorn fart, it's magical and unexpected.",
  "I'm pretty sure this song is the soundtrack to a clown nightmare.",
  "Listening to this song is like trying to follow a squirrel through a maze.",
  "This song is like a Rubik's Cube for my ears, I can't figure it out but I'm still playing with it.",
  "If this song were a person, they would definitely be the class clown.",
  "This song is like a guilty pleasure, but with more cowbell.",
  "I feel like this song was made specifically for me and my weird taste in music.",
  "This song is like a piñata, I don't know what's inside but I want to find out.",
  "If this song were a food, it would be a deep-fried Twinkie.",
  "This song is like a train wreck, I know I shouldn't watch but I can't look away.",
  "This song is like a carnival ride, it's exciting but also slightly terrifying.",
  "I don't know what this song is saying, but I'm pretty sure it involves aliens and/or robots.",
  "Listening to this song is like taking a journey through a rainbow-colored forest.",
  "This song is like a fever dream, it's surreal and a little bit scary.",
  "I'm pretty sure this song was created by an AI, and I'm kind of okay with that.",
  "This song is like a box of chocolates, you never know what you're gonna get.",
];
